import json
import csv
import boto3
import io
import os
from logic_engine import RecommendationEngine
import logging

# Configure Logger
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Initialize clients outside handler for reuse
region_name = os.environ.get("region_name")

bedrock = boto3.client(service_name='bedrock-runtime', region_name=region_name)
s3 = boto3.client('s3') 

def get_user_data(user_id, file_path='input_data_dummy_users.csv'):
    """
    Reads the local CSV file and finds the specific user.
    
    Args: 
        user_id: The unique identifier for the user to retrieve.
        file_path: The local path to the CSV file containing user records.
    Return: 
        dict: The user's data row if found, otherwise None.
    Raises:
        Exception: Logged if there is an error reading the CSV file.
    """
    try:
        # Check if file exists in the deployment package
        if not os.path.exists(file_path):
            logger.info(f"File {file_path} not found.")
            return None

        with open(file_path, mode='r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row['user_id'] == user_id:
                    return row
        return None
    except Exception as e:
        logger.info(f"Error reading CSV: {str(e)}")
        return None

def format_profile_for_llm(row):
    """
    Helper to turn raw CSV data into human-readable context for the prompt.
    
    Args: 
        row: The dictionary containing raw user data from the CSV.
    Return: 
        dict: A formatted dictionary with human-readable financial context.
    Raises:
        ValueError: Description of the exception if income values are not valid numbers.
    """

    is_true = lambda key: str(row.get(key)).strip().upper() == 'TRUE'

    # 1. Determine Goal String
    goal_str = "General Savings"
    if is_true('goal_is_emergency_fund'):
        goal_str = "Build Emergency Fund"
    elif is_true('is_goal_education'):
        goal_str = "Education Savings"
    elif is_true('saving_for_specific_goal'):
        months = row.get('goal_term_months', '0')
        goal_str = f"Specific Goal ({months} months timeline)"

    # 2. Income Context
    personal = float(row.get('personal_income', 0))
    spouse = float(row.get('spouse_income', 0))
    total = personal + spouse
    income_str = f"${total:,.0f} (Household)"
    print("fund emergency:",row.get('has_emergency_fund'))
    return {
        'employment_status': row.get('employment_status'),
        'income_range': income_str,
        'age': row.get('age', 'Unknown'),
        'has_emergency_fund': "Yes" if is_true('has_emergency_fund') else "No",
        'primary_goal': goal_str,
        'marital_status': row.get('marital_status')
    }

def generate_explanation_with_bedrock(profile, recommendation):
    """
    Use Bedrock Claude to generate natural, personalized explanation.
    
    Args: 
        profile: The formatted human-readable user profile dictionary.
        recommendation: The account type string recommended by the engine.
    Return: 
        str: A natural language explanation generated by the LLM.
    Raises:
        Exception: Logged if the Bedrock service call fails.
    """
    try:
        # Build prompt
        prompt = f"""You are a friendly financial advisor explaining account recommendations to a client.

Client Profile:
- Employment: {profile['employment_status']} ({profile['marital_status']})
- Household Income: {profile['income_range']}
- Age: {profile['age']}
- Has Emergency Fund: {profile['has_emergency_fund']}
- Primary Goal: {profile['primary_goal']}

Our Recommendation Engine selected: **{recommendation}**

Task: Write a concise, warm, and clear explanation (max 3 sentences) of WHY this specific account is the best choice for them right now.
Additionally also provide a short reason for why this account is recommended with the reason as the parameters. Like since profile['parameter'] is
greater or less than a value, this is the best choice for you.
Example format:
"Since you are {profile['employment_status']} and saving for {profile['primary_goal']}, we recommend {recommendation}. This account type is ideal because..."

Focus on:
1. Connecting their goal/status to the account type.
2. The logic (e.g., "Since you don't have an emergency fund yet...")
3. Be encouraging.

Do NOT say "Based on the data". Just give the advice naturally in 3 concise sentences upto 100 words.
"""

        model_id = os.environ.get("model_id")
        max_tokens = int(os.environ.get("max_tokens", "200").strip('"'))
        temperature = float(os.environ.get("temperature", "0.7").strip('"'))

        # The Converse API standardizes the request for ALL models
        response = bedrock.converse(
            modelId=model_id,
            messages=[
                {
                    "role": "user",
                    "content": [{"text": prompt}]
                }
            ],
            inferenceConfig={
                "maxTokens": max_tokens,
                "temperature": temperature
            }
        )

        # The response structure is also standardized
        explanation = response['output']['message']['content'][0]['text']
        return explanation
        
    except Exception as e:
        logger.info(f"Error generating explanation: {str(e)}")
        return f"We recommended {recommendation} based on your current goal of {profile['primary_goal']} and your employment status."

def handler(event,context):
    """
    Main Handler for AWS Lambda.
    
    Args: 
        event: The Lambda event containing user_id (directly or in body).
        context: The Lambda execution context.
    Return: 
        dict: StatusCode and JSON body containing the recommendation and explanation.
    Raises:
        Exception: Logged if any critical failure occurs during processing.
    """
    engine = RecommendationEngine()
    try:
        # 1. Parse User ID from Event
        model_id = os.environ.get("model_id")

        if 'body' in event:
            # Handle API Gateway standard format
            body_data = json.loads(event['body']) if isinstance(event['body'], str) else event['body']
            user_id = body_data.get('user_id')
        else:
            # Handle direct Lambda invocation
            user_id = event.get('user_id')

        if not user_id:
            return {'statusCode': 400, 'body': json.dumps("Error: No 'user_id' provided.")}

        logger.info(f"Processing request for: {user_id}")

        # 2. Retrieve User Data from CSV
        user_row = get_user_data(user_id)
        if not user_row:
            return {'statusCode': 404, 'body': json.dumps(f"User {user_id} not found.")}

        # 3. Get Rule-Based Recommendation
        rec_result = engine.recommend(user_row)

        # 4. Prepare Context & Call LLM
        llm_profile = format_profile_for_llm(user_row)
        explanation = generate_explanation_with_bedrock(llm_profile, rec_result)

        # 5. Return JSON Response
        result = {
            "user_id": user_id,
            "profile_summary": llm_profile,
            "recommendation": rec_result,
            "explanation": explanation
        }

        return {
            "statusCode": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "body": result
        }

    except Exception as e:
        logger.info(f"Critical Error: {str(e)}")
        
        return {
            "statusCode": 500,
            "body": json.dumps(f"Internal Server Error: {str(e)}")
        }